
SELECT
CLI_CO_NUMERO,
PRO_CO_NUMERO,
:QTD_RECEBIDA AS QTD_RECEBIDA,
NVL(APLICAR_DESCONTO_DE,0) AS APLICAR_DESCONTO_DE, /*ESSE AQUI É O CARA*/
GGD_CO_NUMERO,
GLD_GRUPO_DESCONTO
FROM
(
    SELECT
    LINHA.GGD_CO_NUMERO AS GGD_CO_NUMERO, 
    LINHA.GLD_GRUPO_DESCONTO AS GLD_GRUPO_DESCONTO, 
    LINHA.PRO_CO_NUMERO AS PRO_CO_NUMERO, 
    LINHA.CLI_CO_NUMERO AS CLI_CO_NUMERO, 
    --SELECIONA O MAIOR DESCONTO ENCONTRADO DE ACORDO COM A QTD_RECEBIDA(INFORMADA):
    MAX( CASE GLP_NU_QUANTIDADE 
               --CASO A QTD_RECEBIDA FOR IGUAL ALGUMA EXISTENTE, TRAGA CORRETAMENTE A CORRESPONDÊNCIA EXATA
                WHEN TO_NUMBER(:QTD_RECEBIDA) THEN GLP_PC_DESCONTO 
                --SENÃO CASO A QTD_RECEBIDA NÃO EXISTA EXATAMENTE NA TABELA ENTÃO RETORNO O REGISTRO MENOR IMEDIATO
                ELSE DECODE(GLP_NU_QUANTIDADE, :QTD_RECEBIDA, GLP_PC_DESCONTO, 
                                (SELECT GLP_PC_DESCONTO FROM GLB_LINHA_DESCONTO_PROGRESSIVO PROG3 
                                        WHERE GLP_NU_QUANTIDADE < TO_NUMBER(:QTD_RECEBIDA) AND ROWNUM = 1))
         END) AS APLICAR_DESCONTO_DE
    
    FROM GLB_GRUPO_DESCONTO GRUPO
    
    INNER JOIN GLB_LINHA_DESCONTO LINHA ON GRUPO.GGD_CO_NUMERO = LINHA.GGD_CO_NUMERO
    LEFT JOIN GLB_LINHA_DESCONTO_PROGRESSIVO PROG ON LINHA.GLD_GRUPO_DESCONTO = PROG.GLD_GRUPO_DESCONTO AND PROG.GLP_IN_STATUS IS NULL
    
    WHERE GRUPO.GGD_TIPO_GRUPO = 'OIT_GSK'
    AND LINHA.PRO_CO_NUMERO = 7153
    AND LINHA.CLI_CO_NUMERO = 377171
    
    GROUP BY LINHA.GGD_CO_NUMERO, LINHA.GLD_GRUPO_DESCONTO, LINHA.PRO_CO_NUMERO,
             LINHA.CLI_CO_NUMERO, PROG.GLP_IN_STATUS

) SUBSELECT